version: "3.8"

services:
  app:
    build: ./app
    container_name: app
    volumes:
      - /app/node_modules/
    ports:
      - 8080:8080

  api:
    build: ./api
    container_name: api
    ports:
      - 3000:3000